### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by hywax** [hywax/mafl#150]
Hello everyone,  
When I was developing Mafl, I didn’t think it would be of interest to anyone else. I created just enough to meet my own needs. However, I see from the activity that others find it useful as well. I've decided to completely rewrite Mafl to make it easily extendable. Most importantly, I aim to simplify the configuration process by adding settings to the web interface.

## Roadmap

- [ ] Complete the migration to Nuxt 4  
- [ ] Switch to `@nuxt/ui` and `@nuxt/ui-pro`  
- [ ] Implement the new `config.yml` format  
- [ ] Add the ability to edit `config.yml` directly from the web interface  
- [ ] Migrate the current services  
- [ ] Write a guide for migrating to the new `config.yml`  

## Breaking Changes

Currently, the `config.yml` format is not extendable. To enable editing it from the web interface, its structure needs to be changed. I apologize in advance for this, but it is a necessary step.

## Development

`0.x` - [https://github.com/hywax/mafl/tree/main](https://github.com/hywax/mafl/tree/main)  
`1.x` - [https://github.com/hywax/mafl/tree/v1](https://github.com/hywax/mafl/tree/v1)

Once `1.x` is created, the code will be moved to the `main` branch.
